/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-11-22 07:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<title>Insert title here</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/profile.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/datepicker.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/bootstrap.css\">\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/script/jquery-1.10.2.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/script/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/script/bootstrap-datepicker.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("   $(document).ready(function () {\n");
      out.write("\t\t$('.datepicker').datepicker();\n");
      out.write("   });\n");
      out.write("   </script>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("      <div class=\"col-md-5  toppad  pull-right col-md-offset-3 \">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/j_spring_security_logout\">Logout</a>\n");
      out.write("       <br>\n");
      out.write("      </div>\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad\" >\n");
      out.write("   \t\t\t<form class=\"form-horizontal\" role=\"form\" name=\"form.profileForm\"  enctype=\"multipart/form-data\" >\n");
      out.write("   \n");
      out.write("          <div class=\"panel panel-info\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Profile</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-2 col-lg-2 \" align=\"center\"> \n");
      out.write("                \t<img alt=\"User Pic\" class=\"img-circle img-responsive\"> <!-- ng-src=\"{{adminUsersDetails.photoPath}}\" ng-src=\"./resources/images/pratik.jpg\"-->\n");
      out.write("                \t<h6>Upload a different photo...</h6>\n");
      out.write("        \t\t\t<!-- <input type=\"file\" class=\"avatar img-circle\" alt=\"avatar\"> -->\n");
      out.write("        \t\t\t<input type=\"file\" class=\"avatar img-circle\" alt=\"avatar\"  name=\"photoPath\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-10 col-lg-10 \"> \n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">First Name:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t\t            <input class=\"form-control\" type=\"text\"  name=\"firstname\" id=\"firstname\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Last Name:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"lastname\" id=\"lastname\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Date Of Birth:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t\t\t\t  <input type=\"text\" class=\"datepicker\" datepicker=\"\" name=\"dateOfBirth\" id=\"dateOfBirth\"> <br>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t         \n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Email:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"emailId\" id=\"emailId\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\t\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Password:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"password\" id=\"password\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Mobile No:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input type=\"text\" class=\"form-control\" name=\"mobileNo\" id=\"mobileNo\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Date Of Joining:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t\t\t\t  <input type=\"text\" class=\"datepicker\" datepicker=\"\" name=\"dateOfJoining\"> <br>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Designation:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"designation\" id=\"designation\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">project:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"project\" >\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Manager:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"manager\" id=\"manager\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Marital Status:</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\n");
      out.write("\t\t\t\t            <label><input type=\"radio\" name=\"maritalStatus\" value=\"married\">Married</label>\n");
      out.write("\t\t\t\t            <label><input type=\"radio\" name=\"maritalStatus\" value=\"unmarried\">Unmarried</label>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Date Of Marriage:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t\t\t\t  <input type=\"text\" class=\"datepicker\" datepicker=\"\" name=\"dateOfMarriage\" id=\"dateOfMarriage\"><br>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t           <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Spause/Parent Name:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"parentName\" id=\"parentName\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t           <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Spause/Parent Contact:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"parentContact\" id=\"parentContact\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Blood group:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"bloodGroup\" id=\"bloodGroup\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Total Year of Exp:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <input class=\"form-control\" type=\"text\" name=\"totalYearOfExperience\" id=\"totalYearOfExperience\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-lg-3 control-label\">Address:</label>\n");
      out.write("\t\t\t            <div class=\"col-lg-8\">\n");
      out.write("\t\t\t              <textarea rows=\"3\" class=\"form-control\" name=\"address\" id=\"address\"></textarea>\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t            <label class=\"col-md-3 control-label\"></label>\n");
      out.write("\t\t\t            <div class=\"col-md-8\">\n");
      out.write("\t\t\t              <input type=\"button\" class=\"btn btn-primary\" value=\"Save Changes\" name=\"save\" id=\"save\">\n");
      out.write("\t\t\t              <span></span>\n");
      out.write("\t\t\t              <input type=\"reset\" class=\"btn btn-default\" value=\"Cancel\">\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t          </div>\n");
      out.write("\t                </div>\n");
      out.write("\t              </div>\n");
      out.write("\t            </div>\n");
      out.write("\t          </div>\n");
      out.write("\t        </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div> \n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
